version: "3.9"

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: chat4all
      POSTGRES_USER: chat4all
      POSTGRES_PASSWORD: chat4all
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  api:
    build: ./api
    depends_on:
      - postgres
      - kafka
      - minio
    ports:
      - "8000:8000"
    environment:
      POSTGRES_DB: chat4all
      POSTGRES_USER: chat4all
      POSTGRES_PASSWORD: chat4all
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      OBJECT_STORAGE_ENDPOINT: "minio:9000"
      OBJECT_STORAGE_PUBLIC_ENDPOINT: "localhost:9000"
      KAFKA_CHAT_TOPIC: chat-messages

      OBJECT_STORAGE_ACCESS_KEY: "chat4all"
      OBJECT_STORAGE_SECRET_KEY: "chat4all123"
      OBJECT_STORAGE_BUCKET_NAME: "chat4all-files"
      OBJECT_STORAGE_SECURE: "0"   # 0 = HTTP, 1 = HTTPS


  minio:
    image: minio/minio:RELEASE.2024-06-13T22-53-53Z
    container_name: chat4all-minio
    environment:
      MINIO_ROOT_USER: chat4all
      MINIO_ROOT_PASSWORD: chat4all123
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"   # API S3
      - "9001:9001"   # Console web
    volumes:
      - minio_data:/data

  worker:
    build: ./worker
    depends_on:
      - postgres
      - kafka
    environment:
      POSTGRES_DB: chat4all
      POSTGRES_USER: chat4all
      POSTGRES_PASSWORD: chat4all
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      KAFKA_CHAT_TOPIC: chat-messages
    # opcional: reiniciar sempre que cair
    restart: unless-stopped

  connector_whatsapp_mock:
    build:
      context: .
      dockerfile: connector_whatsapp_mock/Dockerfile
    depends_on:
      - kafka
    environment:
      KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
      WHATSAPP_OUTBOUND_TOPIC: "whatsapp_outbound"
      WHATSAPP_INBOUND_TOPIC: "whatsapp_inbound"
    ports:
      - "8002:8002"

  connector_instagram_mock:
    build:
      context: .
      dockerfile: connector_instagram_mock/Dockerfile
    depends_on:
      - kafka
    environment:
      KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
      INSTAGRAM_OUTBOUND_TOPIC: "instagram_outbound"
      INSTAGRAM_INBOUND_TOPIC: "instagram_inbound"
    ports:
      - "8003:8003"


  prometheus:
    image: prom/prometheus:v2.54.1
    container_name: chat4all-prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"
    depends_on:
      - api
      - worker

  grafana:
    image: grafana/grafana:11.1.0
    container_name: chat4all-grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    volumes:
      - grafana-data:/var/lib/grafana



volumes:
  pgdata:
  minio_data:
  grafana-data: